<?php

namespace KiriminAja\Unit\Address\DistrictService;

use KiriminAja\Services\Address\DistrictService;
use PHPUnit\Framework\TestCase;

class DistrictServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new DistrictTest())->addressMock()
            ->shouldReceive([
                'districts' => [
                    true,
                    [
                        'status'   => true,
                        'text'     => "success mock",
                        'endpoint' => 'districts',
                        'datas'    => [
                            'id'   => 1234,
                            'name' => "district mock"
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $city_id = 12;
        $result = (new DistrictService($city_id))->call();

        self::assertTrue($result->status);
    }
}
