<?php

namespace KiriminAja\Services\Preference\SetWhitelistExpeditionService;

require_once(__DIR__.'/../PreferenceMock.php');

use KiriminAja\Services\Preference\PreferenceMock;
use KiriminAja\Services\Preference\SetWhitelistExpeditionService;
use PHPUnit\Framework\TestCase;

class SetWhitelistExpeditionServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new PreferenceMock())->preferenceMock()
            ->shouldReceive([
                'setWhiteListExpedition' => [
                    true,
                    [
                        'status' => true,
                        'text'   => "Success to set whitelist",
                        'datas'  => [
                            'id'   => 123,
                            'name' => 'Mock preference data'
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $services = ['jne','sicepat','jnt'];
        $result = (new SetWhitelistExpeditionService($services))->call();

        self::assertTrue($result->status);
        self::assertEquals('Success to set whitelist', $result->message);
        self::assertEquals(null, $result->data);
    }
}
