<?php

namespace KiriminAja\Unit\Shipping\ScheduleService;

use KiriminAja\Services\Shipping\ScheduleService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class ScheduleServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'schedules' => [
                    false,
                    [
                        'status'    => false,
                        'text'      => 'Failed to fetch schedules data'
                    ]
                ]
            ]);
    }

    public function test()
    {
        $result = (new ScheduleService())->call();
        self::assertFalse($result->status);
    }
}
