<?php

namespace KiriminAja\Unit\Shipping\ScheduleService;

use KiriminAja\Services\Shipping\ScheduleService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class ScheduleServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'schedules' => [
                    true,
                    [
                        'status'    => true,
                        'text'      => 'Success to fetch schedules data',
                        'schedules' => [
                            'id'   => 1234,
                            'name' => "schedule 1 mock"
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $result = (new ScheduleService())->call();
        self::assertTrue($result->status);
    }
}
