<?php

namespace KiriminAja\Unit\Shipping\PriceService;

use KiriminAja\Models\ShippingPriceData;
use KiriminAja\Services\Shipping\PriceService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class PriceServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'price' => [
                    false,
                    [
                        'status'  => false,
                        'text'    => 'Failed to get shipping mock data',
                    ]
                ]
            ]);
    }

    public function test()
    {
        $param = new ShippingPriceData();
        $param->courier = ['jne'];
        $param->destination = 'sleman';
        $param->insurance = false;
        $param->item_value = 100000;
        $param->origin = 'bekasi';
        $param->weight = 560;

        $result = (new PriceService($param))->call();
        self::assertFalse($result->status);
    }
}
