<?php

namespace KiriminAja\Unit\Shipping\PriceService;

use KiriminAja\Models\ShippingPriceData;
use KiriminAja\Services\Shipping\PriceService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class PriceServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'price' => [
                    true,
                    [
                        'status'  => true,
                        'text'    => 'Success to get shipping mock data',
                        'details' => [
                            'id' => 1
                        ],
                        'results' => [
                            'id' => 12
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $param = new ShippingPriceData();
        $param->courier = ['jne'];
        $param->destination = 'sleman';
        $param->insurance = false;
        $param->item_value = 100000;
        $param->origin = 'bekasi';
        $param->weight = 560;

        $result = (new PriceService($param))->call();
        self::assertTrue($result->status);
    }
}
