<?php

namespace KiriminAja\Unit\Preference\SetCallbackService;

use KiriminAja\Services\Preference\SetCallbackService;
use KiriminAja\Unit\Preference\PreferenceMock;
use PHPUnit\Framework\TestCase;

class SetCallbackServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new PreferenceMock())->preferenceMock()
            ->shouldReceive([
                'setCallback' => [
                    false,
                    [
                        'status' => false,
                        'text'   => "success get prefence data"
                    ]
                ]
            ]);
    }

    public function test()
    {
        $url = 'https://mock.preference.com';
        $result = (new SetCallbackService($url))->call();
        self::assertFalse($result->status);
    }
}
