<?php

namespace KiriminAja\Unit\Shipping\RequestPickupService;

use KiriminAja\Models\RequestPickupData;
use KiriminAja\Services\Shipping\RequestPickupService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class RequestPickupServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'requestPickup' => [
                    false,
                    [
                        'status' => false,
                        'text'   => 'Failed to fetch shipping pickup data'
                    ]
                ]
            ]);
    }

    public function test()
    {
        $param = new RequestPickupData();
        $result = (new RequestPickupService($param))->call();
        self::assertFalse($result->status);
    }
}
