<?php

namespace KiriminAja\Unit\Shipping\TrackingService;

use KiriminAja\Services\Shipping\TrackingService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class TrackingServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'tracking' => [
                    false,
                    [
                        'status'      => false,
                        'text'        => 'Failed to get tracking data'
                    ]
                ]
            ]);
    }

    public function test()
    {
        $order_id = 'OID-MOCK123';
        $result = (new TrackingService($order_id))->call();
        self::assertFalse($result->status);
    }
}
