<?php

namespace KiriminAja\Unit\Preference\SetWhitelistExpeditionService;

use KiriminAja\Services\Preference\SetWhitelistExpeditionService;
use KiriminAja\Unit\Preference\PreferenceMock;
use PHPUnit\Framework\TestCase;

class SetWhitelistExpeditionServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new PreferenceMock())->preferenceMock()
            ->shouldReceive([
                'setWhiteListExpedition' => [
                    false,
                    [
                        'status' => false,
                        'text'   => "Failed get preference data"
                    ]
                ]
            ]);
    }

    public function test()
    {
        $services = ['jne','sicepat','jnt'];
        $result = (new SetWhitelistExpeditionService($services))->call();
        self::assertFalse($result->status);
    }
}
