<?php

namespace KiriminAja\Unit\Shipping\GetPaymentService;

use KiriminAja\Services\Shipping\GetPaymentService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class GetPaymentServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'payment' => [
                    false,
                    [
                        'status' => false,
                        'text'   => "Failed get shipping payment data"
                    ]
                ]
            ]);
    }

    public function test()
    {
        $payment_id = 123;
        $result = (new GetPaymentService($payment_id))->call();
        self::assertFalse($result->status);
    }
}
