<?php

namespace KiriminAja\Unit\Shipping\GetPaymentService;

use KiriminAja\Services\Shipping\GetPaymentService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class GetPaymentServiceValidationFailTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test()
    {
        $payment_id = 'mock params';
        $result = (new GetPaymentService($payment_id))->call();
        self::assertFalse($result->status);
    }
}
