<?php

namespace KiriminAja\Unit\Shipping\CancelShippingService;

use KiriminAja\Services\Shipping\CancelShippingService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class CancelShippingServiceFailedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'cancel' => [
                    false,
                    [
                        'status' => false,
                        'text'   => "Failed get shipping data"
                    ]
                ]
            ]);
    }

    public function test()
    {
        $awb = 'OID-8372637';
        $reason = 'mock reason';
        $result = (new CancelShippingService($awb, $reason))->call();
        self::assertFalse($result->status);
    }
}
