<?php

namespace KiriminAja\Unit\Shipping\CancelShippingService;

use KiriminAja\Services\Shipping\CancelShippingService;
use KiriminAja\Unit\Shipping\ShipppingMock;
use PHPUnit\Framework\TestCase;

class CancelShippingServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ShipppingMock())->shippingMock()
            ->shouldReceive([
                'cancel' => [
                    true,
                    [
                        'status' => true,
                        'text'   => "Success get shipping data",
                        'data'  => [
                            'id'   => 987,
                            'name' => "shipping mock data"
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $awb = 'OID-8372637';
        $reason = 'mock reason';
        $result = (new CancelShippingService($awb, $reason))->call();
        self::assertTrue($result->status);
    }
}
