<?php

namespace KiriminAja\Unit\Address\ProvinceService;

use KiriminAja\Services\Address\ProvinceService;
use KiriminAja\Unit\Address\AddressMock;
use PHPUnit\Framework\TestCase;

class ProvinceServiceSuccessTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new AddressMock())->addressMock()
            ->shouldReceive([
                'provinces' => [
                    true,
                    [
                        'status' => true,
                        'text'   => 'success get mock data',
                        'datas'  => [
                            'name' => 'data mock 1'
                        ]
                    ]
                ]
            ]);
    }

    public function test()
    {
        $result = (new ProvinceService())->call();

        self::assertTrue($result->status);
    }
}
