name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block at workflow level
permissions:
  contents: read
  checks: write  # Needed for test results

jobs:
  build:
    runs-on: ubuntu-latest-minimal
    strategy:
      matrix:
        php: ['8.0','8.1']
    name: Compability test with php version ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v4
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
